version: '3'
services:
  sabnzbd:
    container_name: sab
    image: linuxserver/sabnzbd
    network_mode: service:gluetun
    volumes:
      - /docker/sabnzbd:/config
      - /downloads/complete:/downloads
      - /downloads/incomplete:/incomplete-downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=American/New_York
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: trans
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - /docker/trans:/config
      - /downloads/incomplete/processing:/downloads/complete
      - /downloads/incomplete/downloading:/downloads/incomplete
    restart: unless-stopped
  docker-av:
    image: rordi/docker-antivirus
    container_name: docker-av
    volumes:
      - /downloads/incomplete/processing:/data/av/queue
      - /downloads/complete:/data/av/ok
      - /downloads/avCheck/bad:/data/av/nok
      - /downloads/avCheck/quarantine:/data/av/quarantine
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 # SabNZBD
      - 9091:9091 #transmission
      - 51413:51413 #transmission
      - 51413:51413/udp #transmission
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER= #username
      - OPENVPN_PASSWORD= #Password
      - SERVER_COUNTRIES=Switzerland
    restart: unless-stopped