version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/sonarr:/config
      - /media/series:/tv
      - /downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/radarr:/config
      - /media/movies:/movies
      - /downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI
      - 8266:8266 # Server
      - 8267:8267 # Internal
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=192.168.1.11
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /docker/tdarr/server:/app/server      
      - /docker/tdarr/configs:/app/configs      
      - /docker/tdarr/logs:/app/logs
      - /media/movies:/movies
      - /docker/tmp/transcode:/temp

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeID=MainNode
      - serverIP=192.168.1.11
      - serverPort=8266
    volumes:
      - /docker/tdarr/server:/app/server      
      - /docker/tdarr/configs:/app/configs      
      - /docker/tdarr/logs:/app/logs
      - /media/movies:/movies
      - /docker/tmp/transcode:/temp