version: '3'
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      - TZ=American/New_York
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
 
# Port 53 is being used at your host machine by default.
# To find what is using port 53:
#
#     sudo lsof -i -P -n | grep LISTEN
#
# If 'systemd-resolved' is what is listening to port 53, you need to disable it:
# 
#     systemctl disable systemd-resolved.service
#     systemctl stop systemd-resolved
#
# Now you have port 53 open, but no dns configured for your host. 
# You need to edit '/etc/resolv.conf' and add a DNS address:
#
#      nameserver 8.8.8.8
#
# Once pihole is running, you can change the dns server of your host to localhost.
# Change again '/etc/resolv.conf' to:
# 
#      nameserver 127.0.0.1
