version: "3"

services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: Virgil
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - '/docker/pihole/etc/pihole:/etc/pihole'
      - '/docker/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  nodeexp:
    image: prom/node-exporter
    container_name: nodeexp
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
